export type TopMode = "date" | "couples" | "friends" | "family";
export type FriendSubMode =
  | "football"
  | "tv-movies"
  | "beauty"
  | "music"
  | "gaming"
  | "wyr"
  | "travel"
  | "food";
export type AnyMode = TopMode | FriendSubMode;

export interface ModeConfig {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  bgClass: string;
  accent: string;
  accentSoft: string;
  text: string;
  ring: string;
}

export const MODES: Record<TopMode, ModeConfig> = {
  date: {
    id: "date",
    name: "Date Mode",
    emoji: "💘",
    tagline: "Discover each other deeper.",
    bgClass: "bg-mode-date",
    accent: "bg-indigo-500 hover:bg-indigo-600",
    accentSoft: "bg-indigo-100",
    text: "text-indigo-600",
    ring: "ring-indigo-200",
  },
  couples: {
    id: "couples",
    name: "Couples / Married",
    emoji: "🔥",
    tagline: "Reignite the spark.",
    bgClass: "bg-mode-couples",
    accent: "bg-rose-500 hover:bg-rose-600",
    accentSoft: "bg-rose-100",
    text: "text-rose-600",
    ring: "ring-rose-200",
  },
  friends: {
    id: "friends",
    name: "Friends Mode",
    emoji: "👥",
    tagline: "Fun questions for any group.",
    bgClass: "bg-mode-friends",
    accent: "bg-violet-500 hover:bg-violet-600",
    accentSoft: "bg-violet-100",
    text: "text-violet-600",
    ring: "ring-violet-200",
  },
  family: {
    id: "family",
    name: "Family Time",
    emoji: "👨‍👩‍👧",
    tagline: "Real moments with those you love.",
    bgClass: "bg-mode-family",
    accent: "bg-emerald-500 hover:bg-emerald-600",
    accentSoft: "bg-emerald-100",
    text: "text-emerald-600",
    ring: "ring-emerald-200",
  },
};

export interface SubModeConfig {
  id: FriendSubMode;
  name: string;
  emoji: string;
  bgClass: string;
  accent: string;
  accentSoft: string;
  text: string;
  ring: string;
}

export const FRIEND_SUBMODES: Record<FriendSubMode, SubModeConfig> = {
  football: {
    id: "football",
    name: "Football",
    emoji: "⚽",
    bgClass: "bg-mode-friends",
    accent: "bg-green-600 hover:bg-green-700",
    accentSoft: "bg-green-100",
    text: "text-green-700",
    ring: "ring-green-200",
  },
  "tv-movies": {
    id: "tv-movies",
    name: "TV & Movies",
    emoji: "📺",
    bgClass: "bg-mode-friends",
    accent: "bg-sky-500 hover:bg-sky-600",
    accentSoft: "bg-sky-100",
    text: "text-sky-600",
    ring: "ring-sky-200",
  },
  beauty: {
    id: "beauty",
    name: "Beauty",
    emoji: "💄",
    bgClass: "bg-mode-friends",
    accent: "bg-pink-500 hover:bg-pink-600",
    accentSoft: "bg-pink-100",
    text: "text-pink-600",
    ring: "ring-pink-200",
  },
  music: {
    id: "music",
    name: "Music",
    emoji: "🎵",
    bgClass: "bg-mode-friends",
    accent: "bg-purple-500 hover:bg-purple-600",
    accentSoft: "bg-purple-100",
    text: "text-purple-600",
    ring: "ring-purple-200",
  },
  gaming: {
    id: "gaming",
    name: "Gaming",
    emoji: "🎮",
    bgClass: "bg-mode-friends",
    accent: "bg-indigo-600 hover:bg-indigo-700",
    accentSoft: "bg-indigo-100",
    text: "text-indigo-600",
    ring: "ring-indigo-200",
  },
  wyr: {
    id: "wyr",
    name: "Would You Rather",
    emoji: "🎲",
    bgClass: "bg-mode-friends",
    accent: "bg-amber-500 hover:bg-amber-600",
    accentSoft: "bg-amber-100",
    text: "text-amber-600",
    ring: "ring-amber-200",
  },
  travel: {
    id: "travel",
    name: "Travel",
    emoji: "✈️",
    bgClass: "bg-mode-friends",
    accent: "bg-cyan-500 hover:bg-cyan-600",
    accentSoft: "bg-cyan-100",
    text: "text-cyan-600",
    ring: "ring-cyan-200",
  },
  food: {
    id: "food",
    name: "Food & Drink",
    emoji: "🍕",
    bgClass: "bg-mode-friends",
    accent: "bg-orange-500 hover:bg-orange-600",
    accentSoft: "bg-orange-100",
    text: "text-orange-600",
    ring: "ring-orange-200",
  },
};

export const FREE_QUESTIONS = 7;

export function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export const DEEP_DIVE_PROMPTS = [
  "Now answer that again — but be 3× more honest.",
  "What's the thing you're NOT saying about that answer?",
  "If your best friend described your answer, what would they say?",
  "What does that reveal about what you value most?",
  "If you could change your answer, what would you change — and why?",
  "What would your 10-years-younger self think of that answer?",
  "What's the boldest, most vulnerable version of that answer?",
  "What fear is hiding somewhere behind that answer?",
  "What would you say if you knew nobody here would ever repeat it?",
  "If you had to act on that answer starting tomorrow, what would you do?",
];

export const QUESTIONS: Record<AnyMode, string[]> = {
  date: [
    "What's something you've never told anyone on a first date?",
    "What's the most embarrassing thing that happened to you in school?",
    "If you could relive one day of your life, which would it be?",
    "What's something you used to believe that now seems ridiculous?",
    "What's your most irrational fear?",
    "Who in your life has shaped you the most?",
    "What's the wildest thing on your bucket list?",
    "When did you last cry, and why?",
    "What's a secret talent nobody knows you have?",
    "What does your perfect day look like from start to finish?",
    "What's a deal-breaker you've learned about yourself through experience?",
    "What would your childhood self think of who you are today?",
    "What's a belief you hold that most people around you don't share?",
    "What's something you're still working on accepting about yourself?",
    "If you could change one thing about how you grew up, what would it be?",
    "What's the kindest thing a stranger has ever done for you?",
    "What's your love language, and do you feel like you get it?",
    "What's a memory that still makes you laugh out loud?",
    "What's the most spontaneous thing you've ever done?",
    "What's something you're genuinely proud of that you rarely talk about?",
    "Who's the most interesting person you've ever met?",
    "What do you think about most when you can't sleep?",
    "What's a small thing that always cheers you up, no matter what?",
    "What's the hardest thing you've ever had to forgive?",
    "If you could have dinner with any person, dead or alive, who would it be?",
    "What's a chapter of your life you'd title 'The Turning Point'?",
    "What's something you're secretly really good at?",
    "How do you recharge when life gets overwhelming?",
    "What's a question you wish someone would ask you more often?",
    "What's one thing you want the person across from you to know about you?",
  ],
  couples: [
    "What was your first impression of me?",
    "What's something I do that makes you fall for me all over again?",
    "Where do you see us in 5 years?",
    "What's one thing you wish I understood better about you?",
    "What's the best memory we've made together so far?",
    "What's a tiny moment with me you replay in your head?",
    "What's something you've been wanting to ask but haven't?",
    "What does feeling loved by me look like to you?",
    "What's a dream you've never shared with me?",
    "What's one ritual you'd like us to start together?",
    "What's one small thing I do that makes you feel truly seen?",
    "What's a challenge we've overcome that made us stronger?",
    "Where would you most love to travel with me?",
    "What's something about our relationship that surprised you?",
    "What's the funniest miscommunication we've ever had?",
    "What's the most thoughtful thing I've ever done for you?",
    "What does our future home look like in your imagination?",
    "What's something we've never done together that you'd love to try?",
    "What's a habit of mine you find secretly adorable?",
    "How have I grown the most since we've been together?",
    "What's a fear about us you've never said out loud?",
    "If we had to describe our relationship in three words, what would yours be?",
    "What's something you want to be better at as a partner?",
    "What's a conversation we've been avoiding that we should have?",
    "What's a compliment you think about giving me but never say?",
    "What's your favourite 'us' memory from the last year?",
    "What song reminds you of us?",
    "How do you know when I'm happy vs. just content?",
    "What do you hope never changes about us?",
    "What's one thing you'd want to be remembered for in this relationship?",
  ],
  friends: [],
  family: [
    "What's your happiest childhood memory?",
    "If you could have any superpower, what would it be and why?",
    "What's one thing you're really proud of yourself for?",
    "If you could travel anywhere in the world tomorrow, where would you go?",
    "What's something you've always wanted to learn?",
    "What family tradition means the most to you?",
    "What's a story about our family you love telling?",
    "Who has shaped who you are today the most?",
    "What's something you hope we always do together?",
    "What's a piece of advice you'd give your younger self?",
    "If you could only keep 3 things in your room, what would they be?",
    "What makes you feel proud of our family?",
    "What's something you'd like to change about your daily routine?",
    "If our family had a motto, what would it be?",
    "What's the best meal we've ever had together?",
    "If you could invent something to help families, what would it be?",
    "What's a kindness someone in this family showed you that you'll never forget?",
    "If you could add one room to our home, what would it be and why?",
    "What does a perfect weekend with family look like to you?",
    "What's one thing you want to get better at this year?",
    "What's the most beautiful place you've ever seen?",
    "What's something you wish grown-ups understood about being a kid?",
    "What's a question you've always wanted to ask someone in this family?",
    "What's one thing that always makes you feel better when you're sad?",
    "If you could have any pet, what would it be and why?",
    "What's something you're grateful for today?",
    "If you could change one rule in our house, what would it be?",
    "What's one word that describes our family perfectly?",
    "If our family were a TV show, what would it be called?",
    "What's something you want to do with the whole family before the year ends?",
  ],
  football: [
    "Which country won the first ever FIFA World Cup in 1930?",
    "Who has won the most Ballon d'Or awards in history?",
    "Which club has won the most UEFA Champions League titles?",
    "Who scored the famous 'Hand of God' goal in 1986?",
    "Which player is known as 'The Egyptian King'?",
    "Which country has won the most FIFA World Cups?",
    "Who is the all-time top scorer in the Premier League?",
    "Which African nation reached the 2022 World Cup semi-finals?",
    "Who scored the winning goal in the 2014 World Cup final?",
    "Which club did Zinedine Zidane play for before Real Madrid?",
    "What year did Leicester City win the Premier League title?",
    "Which player has scored the most goals in a single calendar year?",
    "What is the nickname of the Brazilian national team?",
    "Who won the 2022 FIFA World Cup?",
    "Which country has hosted the World Cup the most times?",
    "What does VAR stand for?",
    "Who is the all-time top scorer for Germany's national team?",
    "Which club has the most Premier League titles ever?",
    "In what year did the offside rule first change to the modern version?",
    "Which country does Sadio Mané play for?",
    "What is Cristiano Ronaldo's nationality?",
    "Who invented the bicycle kick technique?",
    "Which club did Messi spend most of his career at?",
    "What is the maximum number of substitutions allowed in a match now?",
    "Which team won the first ever Women's World Cup in 1991?",
    "What position does a libero play in football?",
    "Who holds the record for most appearances in the Champions League?",
    "Which Spanish club is nicknamed 'Los Blancos'?",
    "What's the name of the trophy given to the World Cup winner?",
    "Which country won Euro 2020 (played in 2021)?",
  ],
  "tv-movies": [
    "What's a movie that genuinely changed how you see the world?",
    "Which TV show universe would you most want to live in?",
    "Name a villain you secretly rooted for.",
    "What's the most overrated show everyone loves but you can't stand?",
    "If your life were a movie, which genre would it be?",
    "Which character from any show or movie do you identify with most?",
    "What's a movie ending that still haunts you?",
    "Which remake was actually better than the original?",
    "What show got you through a really tough time?",
    "If you could unmatch any two actors from a film, who would they be?",
    "What's the most underrated film nobody talks about?",
    "Which actor could play you in the movie of your life?",
    "What's a scene from a movie that always makes you cry?",
    "What show do you think should have ended earlier?",
    "If you could live in any TV show's world for a week, which would it be?",
    "What's the worst movie you've ever enjoyed?",
    "Which TV show had the best finale ever?",
    "What's a film you refuse to rewatch because it was too emotional?",
    "If you had to watch one movie on repeat for a month, which would you pick?",
    "What book adaptation actually did the book justice?",
    "Which fictional family would you most want to be part of?",
    "What's a quote from a movie or show that stuck with you forever?",
    "Which sequel was better than the original?",
    "What's your guilty pleasure TV show you watch alone?",
    "Which child actor grew up to be the most impressive adult actor?",
    "What's a TV show cliffhanger that still annoys you?",
    "Which director's style do you love even before seeing the movie?",
    "What's a foreign language film that blew you away?",
    "Which TV character had the best glow-up across a series?",
    "What's a movie you watched as a kid that hits totally differently now?",
  ],
  beauty: [
    "What's your most controversial fashion opinion?",
    "What's a beauty trend you tried that you now regret?",
    "Which celebrity's style do you secretly copy?",
    "What's the one item in your closet you'd never donate even if it doesn't fit?",
    "What's the worst haircut you ever had?",
    "If money were no object, what would your dream outfit look like?",
    "What beauty product are you embarrassed to admit you can't live without?",
    "Which fashion era do you wish came back?",
    "What's the most you've ever spent on something to wear?",
    "What's your honest opinion on fast fashion?",
    "What's a fashion rule you break on purpose?",
    "Which colour could you never wear and why?",
    "What's the worst beauty advice you've ever followed?",
    "What's a skincare step most people skip but shouldn't?",
    "Which decade's beauty looks do you think aged the worst?",
    "What's the most dramatic physical change you've made to yourself?",
    "What's one beauty trend you wish would just die?",
    "What's a compliment about your appearance you still think about?",
    "If you had to wear one outfit every day for a week, what would it be?",
    "What's the one beauty product you'd take to a desert island?",
    "Which celebrity's style transformation surprised you the most?",
    "What's your signature scent and what does it say about you?",
    "Do you dress for yourself or for others? Be honest.",
    "What's the most you've ever changed your look after a breakup?",
    "What's a fashion trend from your teens that you cringe at now?",
    "What's the most complimented piece of clothing you own?",
    "Which fashion brand do you think is massively overrated?",
    "What does your ideal Sunday outfit look like?",
    "What's one piece of beauty advice you'd give your younger self?",
    "If you had your own clothing line, what would it be called?",
  ],
  music: [
    "What song would play at the movie of your life?",
    "Which artist's music do you hide from your friends?",
    "What's a song that makes you cry every time?",
    "Which concert was the best you've ever been to?",
    "What's the most overrated song of all time?",
    "If you could master one instrument, what would it be?",
    "What's your guiltiest musical pleasure?",
    "Which decade had the best music, and why?",
    "What song do you always skip but would never delete?",
    "If you could erase one song from existence, what would it be?",
    "What song instantly takes you back to a specific memory?",
    "Which artist do you think is criminally underrated?",
    "What's the first album you ever bought or owned?",
    "If you could only listen to one genre for the rest of your life, which would it be?",
    "What's a song you're embarrassed to admit you know every word to?",
    "Which musician's death hit you hardest?",
    "What's the best song to drive to at night?",
    "Which live performance from history do you wish you could have been at?",
    "What song do you play when you need to feel powerful?",
    "What's a song that perfectly describes your current life?",
    "Which music collab was surprisingly great?",
    "What's a lyric that lives in your head rent-free?",
    "Which music era do you think was the most creatively diverse?",
    "If your taste in music reveals your personality, what does yours say about you?",
    "What's the most you've ever paid for concert tickets?",
    "Which album could you listen to from start to finish without skipping?",
    "Who do you think is the greatest musical artist of all time?",
    "What's the weirdest song you genuinely love?",
    "What's your go-to song when you need cheering up?",
    "If you could duet with any artist, who would it be?",
  ],
  gaming: [
    "What's the video game that consumed the most hours of your life?",
    "What's a game you rage-quit and never went back to?",
    "Do you think gaming is a sport? Defend your answer.",
    "Which game character would make the best real-life friend?",
    "What's the most embarrassing game you've ever been caught playing?",
    "Console or PC — and defend your answer.",
    "What game would you pick if you could only play one for the rest of your life?",
    "Which game had the best storyline you've ever experienced?",
    "What's something you wish non-gamers understood about gaming?",
    "If you could live inside any game world, which would it be?",
    "What's the most you've ever spent on in-game purchases?",
    "Which game do you think has the best music soundtrack?",
    "What's the most competitive you've ever gotten over a game?",
    "Which gaming trend do you hate the most?",
    "What's the first video game you ever played?",
    "If gaming were an Olympic sport, which game would you compete in?",
    "What's the most difficult game you've ever completed?",
    "Which game would make the best movie adaptation?",
    "What's your hottest take about the gaming industry?",
    "Which fictional game from a movie or show do you wish was real?",
    "What's the most frustrating boss fight you've ever had?",
    "If you were a game character, what would your special ability be?",
    "Which gaming company do you trust the most?",
    "What's a game you loved as a kid that you tried recently and it doesn't hold up?",
    "What's the most impressive speedrun fact you know?",
    "What gaming achievement are you most proud of?",
    "Which game world has the best lore?",
    "What's the most hours you've ever put into a game in one sitting?",
    "If you could design your own game, what genre would it be?",
    "What's a game you'd recommend to someone who claims they hate gaming?",
  ],
  wyr: [
    "Would you rather always speak in rhymes or always sing your words?",
    "Would you rather know every language or play every instrument perfectly?",
    "Would you rather live without music or without internet for the rest of your life?",
    "Would you rather be the funniest person in the room or the smartest?",
    "Would you rather have unlimited money in a place you hate, or little money in a place you love?",
    "Would you rather know when you're going to die, or how?",
    "Would you rather be 10 minutes late everywhere or 2 hours early everywhere?",
    "Would you rather lose all your memories or never make new ones?",
    "Would you rather be famous for something embarrassing or anonymous for something great?",
    "Would you rather always feel too hot or always feel too cold?",
    "Would you rather have no social media or no Netflix for a year?",
    "Would you rather be able to fly or be invisible?",
    "Would you rather never be able to lie or never be able to tell the truth?",
    "Would you rather live in the past or the future?",
    "Would you rather be the best player on a losing team or the worst player on a winning team?",
    "Would you rather eat your least favourite food every day or never eat your favourite again?",
    "Would you rather always have to whisper or always have to shout?",
    "Would you rather be able to stop time or travel through it?",
    "Would you rather have 10 good friends or 1 best friend?",
    "Would you rather know all the secrets of the universe or relive your happiest day forever?",
    "Would you rather be completely honest for a day or completely dishonest?",
    "Would you rather only be able to watch one show forever or never watch TV again?",
    "Would you rather be 10 years older or 5 years younger than you are now?",
    "Would you rather speak every language or talk to animals?",
    "Would you rather have unlimited free flights or free food for life?",
    "Would you rather live without air conditioning or without heating?",
    "Would you rather be the first person on Mars or discover life in the ocean?",
    "Would you rather work your dream job for no pay or a job you hate for great pay?",
    "Would you rather always know what people are thinking or never know?",
    "Would you rather have a photographic memory or the ability to forget anything on demand?",
  ],
  travel: [
    "Where in the world would you move tomorrow if you could?",
    "What's the most underrated destination you've ever visited?",
    "What's the worst travel experience that became your best story?",
    "Luxury resort or backpacking adventure — which and why?",
    "What's on your travel bucket list that most people would find boring?",
    "What cultural experience abroad completely changed your perspective?",
    "If you had to eat one country's food forever, which would it be?",
    "What's the most beautiful thing you've ever seen while traveling?",
    "Would you rather explore space or the deep ocean?",
    "What's a place you've been that you'd never return to — and why?",
    "What's the strangest thing you've eaten while traveling?",
    "Which country do you think has the friendliest locals?",
    "What's a travel mistake that turned into a great adventure?",
    "If you could speak one language fluently just for travel, which would you choose?",
    "What's the longest you've gone without a proper night's sleep while traveling?",
    "Which country surprised you most compared to your expectations?",
    "What's a travel tradition you always stick to?",
    "If you could teleport to one destination right now, where would you go?",
    "What's the most romantic city you've ever visited?",
    "What's something locals do that tourists always miss?",
    "Window or aisle seat — and is it worth fighting over?",
    "What's the most you've ever paid for a flight, and was it worth it?",
    "Which country do you think has the best public transport?",
    "What's the best sunrise or sunset you've ever witnessed?",
    "If you could live abroad for one year, where would you choose?",
    "What's a place you visited that immediately felt like home?",
    "What's the most interesting person you've met while traveling?",
    "What travel item do you never leave home without?",
    "What's the most culture shock you've ever experienced?",
    "If you could design your perfect travel day from start to finish, what would it include?",
  ],
  food: [
    "What's the most adventurous thing you've ever eaten?",
    "What food do you secretly hate that everyone else loves?",
    "If you could only eat at one restaurant for the rest of your life, which would it be?",
    "What's your most controversial food opinion that you're willing to die on?",
    "What's a dish from your childhood you'd pay anything to eat again?",
    "Sweet or savory? Give your best argument.",
    "What's the most impressive thing you can cook?",
    "What food trend do you wish would just disappear?",
    "If you could have any chef cook for you tonight, who would it be?",
    "What's the meal you'd request for your last dinner on earth?",
    "What's the most you've ever spent on a single meal?",
    "Which cuisine do you think is massively underrated?",
    "What's a food combination people think is weird but you love?",
    "What's the best meal you've ever cooked from scratch?",
    "If you could ban one ingredient from existence, what would it be?",
    "Which country do you think has the best street food?",
    "What's the most embarrassing thing you've ever eaten out of laziness?",
    "Pineapple on pizza — defend your position.",
    "What's a dish you've always wanted to learn to make?",
    "What's the most you've ever eaten at one sitting?",
    "Which fast food chain would you be devastated to see close forever?",
    "What's the most overrated restaurant everyone recommends?",
    "What's your secret ingredient that makes your cooking special?",
    "What's the weirdest food craving you've ever had?",
    "If you had to eat only food from one country for the rest of your life, which?",
    "What's the best breakfast you've ever had?",
    "What cooking skill do you wish you had?",
    "What's a food you hated as a kid but love now?",
    "If you opened a restaurant, what would you serve?",
    "What's the perfect comfort food after a terrible day?",
  ],
};

export type FamilyAgeGroup = "young" | "older" | "teen" | "mixed";

export const FAMILY_QUESTIONS: Record<FamilyAgeGroup, string[]> = {
  young: [
    "If you could have any superpower, what would it be?",
    "What animal would you most like to be for a day?",
    "If you had a magic wand, what's the first thing you'd do?",
    "What's the funniest thing that ever happened to you?",
    "If you could fly anywhere right now, where would you go?",
    "What's your favourite thing about our family?",
    "If you could have any pet in the world, what would it be?",
    "What's the bravest thing you've ever done?",
    "If you could meet any cartoon character, who would it be?",
    "What's your favourite thing to do on a rainy day?",
    "If you were in charge for a day, what would you do first?",
    "What's the silliest thing that ever made you laugh?",
    "If you could build anything, what would you build?",
    "What makes you feel really happy inside?",
    "If you could have a room full of one thing, what would it be?",
    "What's your favourite memory with someone in this family?",
    "If you could make up a holiday, what would it celebrate?",
    "What would your dream tree house look like?",
    "What's something you'd love to learn how to do?",
    "If you could eat one food forever, what would it be?",
    "What's the nicest thing someone has ever done for you?",
    "What's your favourite game to play and why?",
    "If you could swap lives with anyone for one day, who would it be?",
    "What's something that always cheers you up when you feel sad?",
    "What do you want to be when you grow up?",
    "If you had a magic door that went anywhere, where would it lead?",
    "What's your favourite thing to do with the whole family?",
    "If you could invent a new toy, what would it do?",
    "What's one kind thing you did for someone this week?",
    "If you could talk to animals, what would you ask them?",
  ],
  older: [
    "What's something you've learned recently that surprised you?",
    "What's the hardest thing about being your age right now?",
    "If you could change one thing about school, what would it be?",
    "What's a goal you have for this year?",
    "What do you think makes someone a truly good friend?",
    "What's something you're really proud of that you haven't told us?",
    "If you could invent anything, what problem would it solve?",
    "What's one thing you wish grown-ups understood about kids?",
    "What's a moment when you felt really brave?",
    "If you could live anywhere in the world, where would you choose?",
    "What's a skill you'd love to have by the time you're 18?",
    "What does your perfect day look like from start to finish?",
    "If you wrote a book, what would it be about?",
    "What's the most interesting fact you know?",
    "What's something you're curious about that you'd love to explore?",
    "If you could meet any famous person alive or in history, who would it be?",
    "What's something you want people to remember about you?",
    "If you could design the perfect school, what would it be like?",
    "What's something you were scared of that you managed to get over?",
    "What's a question you've always wanted to ask someone in this family?",
    "What do you think is the most important invention in history?",
    "If you could make one rule the whole world had to follow, what would it be?",
    "What's something about yourself you're really proud of?",
    "What's the most beautiful place you've ever been?",
    "What's a challenge you're working on right now?",
    "What's something that made you laugh this week?",
    "If you could have dinner with anyone, who would you choose?",
    "What's something kind you did for someone recently?",
    "What's a tradition in this family you hope we keep forever?",
    "What's one thing you'd change about the world if you could?",
  ],
  teen: [
    "What's something you believe that most people your age don't?",
    "What does success mean to you — honestly?",
    "Who in your life has most changed how you see things?",
    "What would you do differently if you weren't worried about what others think?",
    "What's a value you hold that you'd never give up, no matter what?",
    "What do you think your future self wishes you knew right now?",
    "What's something about yourself you're still trying to figure out?",
    "What's the most important thing you've learned from a mistake?",
    "What are you genuinely passionate about that people don't take seriously enough?",
    "What does real friendship mean to you now vs. when you were younger?",
    "What's a fear you're actively trying to face?",
    "What's something you've completely changed your mind about recently?",
    "What's a question you keep coming back to that you haven't answered yet?",
    "What do you think is the most underrated thing in life?",
    "What's something about the world you want to change?",
    "What's a moment that changed how you see yourself?",
    "What's one thing you want this family to know about you?",
    "What do you think is the biggest myth about being a teenager?",
    "What's something you're actively working to get better at?",
    "What's something a stranger said to you that stuck with you?",
    "What does home mean to you?",
    "What's a question you wish someone would ask you more often?",
    "What's something you'd say to your 10-year-old self?",
    "What's a challenge you're facing right now that you haven't talked about?",
    "What do you think makes a relationship — any relationship — actually last?",
    "What's something you're proud of that took real effort?",
    "What's your relationship with failure — does it stop you or push you?",
    "What's something you used to care about that doesn't matter to you anymore?",
    "If you could have one honest conversation with anyone in history, who would it be?",
    "What do you think you'll look back on from this time in your life and be glad about?",
  ],
  mixed: [
    "What's your happiest childhood memory?",
    "If you could have any superpower, what would it be and why?",
    "What's one thing you're really proud of yourself for?",
    "If you could travel anywhere in the world tomorrow, where would you go?",
    "What's something you've always wanted to learn?",
    "What family tradition means the most to you?",
    "What's a story about our family you love telling?",
    "Who has shaped who you are today the most?",
    "What's something you hope we always do together?",
    "What's a piece of advice you'd give your younger self?",
    "If you could only keep 3 things in your room, what would they be?",
    "What makes you feel proud of our family?",
    "If our family had a motto, what would it be?",
    "What's the best meal we've ever had together?",
    "What's a kindness someone in this family showed you that you'll never forget?",
    "If you could add one room to our home, what would it be and why?",
    "What does a perfect weekend with family look like to you?",
    "What's one thing you want to get better at this year?",
    "What's the most beautiful place you've ever seen?",
    "What's a question you've always wanted to ask someone in this family?",
    "What's one thing that always makes you feel better when you're sad?",
    "If you could have any pet, what would it be and why?",
    "What's something you're grateful for today?",
    "If you could change one rule in our house, what would it be?",
    "What's one word that describes our family perfectly?",
    "If our family were a TV show, what would it be called?",
    "What's something you want to do with the whole family before the year ends?",
    "What's the funniest thing that's ever happened in this family?",
    "What's something you love about each person here?",
    "If you could relive one family memory, which would it be?",
  ],
};

export const FRIEND_SUBMODE_LIST: FriendSubMode[] = [
  "football",
  "tv-movies",
  "beauty",
  "music",
  "gaming",
  "wyr",
  "travel",
  "food",
];

export interface QuizQuestion {
  q: string;
  options: [string, string, string, string];
  answer: number;
}

export const QUIZ_QUESTIONS: Partial<Record<FriendSubMode, QuizQuestion[]>> = {
  football: [
    { q: "Which club has won the most UEFA Champions League titles?", options: ["Barcelona", "Real Madrid", "Bayern Munich", "Liverpool"], answer: 1 },
    { q: "Who is the all-time top scorer in the Premier League?", options: ["Wayne Rooney", "Andrew Cole", "Alan Shearer", "Frank Lampard"], answer: 2 },
    { q: "Which country won the 2022 FIFA World Cup?", options: ["France", "Brazil", "Argentina", "Germany"], answer: 2 },
    { q: "How many players does each team have on a football pitch?", options: ["10", "11", "12", "9"], answer: 1 },
    { q: "Which club is nicknamed 'The Red Devils'?", options: ["Arsenal", "Liverpool", "AC Milan", "Manchester United"], answer: 3 },
    { q: "Who won the 2022/23 UEFA Champions League?", options: ["Real Madrid", "Manchester City", "Inter Milan", "PSG"], answer: 1 },
    { q: "Which stadium is known as 'The Theatre of Dreams'?", options: ["Anfield", "Old Trafford", "Stamford Bridge", "Emirates Stadium"], answer: 1 },
    { q: "Which nation has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Italy", "Brazil"], answer: 3 },
    { q: "Who scored the famous 'Hand of God' goal?", options: ["Pelé", "Ronaldo", "Maradona", "Zidane"], answer: 2 },
    { q: "Which club has won the most La Liga titles?", options: ["Barcelona", "Real Madrid", "Atlético Madrid", "Sevilla"], answer: 1 },
    { q: "How many substitutes are allowed in modern professional football?", options: ["3", "4", "5", "6"], answer: 2 },
    { q: "Who was the top scorer at the 2022 FIFA World Cup?", options: ["Lionel Messi", "Kylian Mbappé", "Olivier Giroud", "Lautaro Martínez"], answer: 1 },
    { q: "Lionel Messi has won the Ballon d'Or how many times?", options: ["5", "6", "7", "8"], answer: 3 },
    { q: "Which country does Cristiano Ronaldo play for?", options: ["Spain", "Brazil", "Italy", "Portugal"], answer: 3 },
    { q: "What colour card results in a player being sent off immediately?", options: ["Yellow", "Orange", "Red", "Blue"], answer: 2 },
  ],
  "tv-movies": [
    { q: "Which movie won Best Picture at the 2020 Academy Awards?", options: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], answer: 2 },
    { q: "Who plays Tony Stark / Iron Man in the MCU?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: 1 },
    { q: "How many seasons does Game of Thrones have?", options: ["6", "7", "8", "9"], answer: 2 },
    { q: "Which show features the fictional Dunder Mifflin Paper Company?", options: ["Parks and Rec", "Brooklyn Nine-Nine", "The Office", "Arrested Development"], answer: 2 },
    { q: "Who directed Titanic and Avatar?", options: ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Ridley Scott"], answer: 2 },
    { q: "What is Ross and Monica's surname in Friends?", options: ["Bing", "Green", "Geller", "Buffay"], answer: 2 },
    { q: "Which movie features the line 'I'll be back'?", options: ["RoboCop", "The Terminator", "Predator", "Total Recall"], answer: 1 },
    { q: "Which streaming service produced 'Stranger Things'?", options: ["HBO Max", "Disney+", "Amazon Prime", "Netflix"], answer: 3 },
    { q: "What year was the first Star Wars film released?", options: ["1975", "1977", "1979", "1981"], answer: 1 },
    { q: "Who voices Woody in Toy Story?", options: ["Tom Hanks", "Tim Allen", "Bill Murray", "Robin Williams"], answer: 0 },
    { q: "In Breaking Bad, Walter White was originally a what?", options: ["Lawyer", "Doctor", "Chemistry teacher", "Police officer"], answer: 2 },
    { q: "Which actress plays Katniss in The Hunger Games?", options: ["Kristen Stewart", "Emma Stone", "Jennifer Lawrence", "Scarlett Johansson"], answer: 2 },
    { q: "The TV show 'The Crown' is about which royal family?", options: ["Spanish", "Swedish", "Dutch", "British"], answer: 3 },
    { q: "What is the highest-grossing movie of all time (not inflation-adjusted)?", options: ["Avengers: Endgame", "Titanic", "Avatar: The Way of Water", "Top Gun: Maverick"], answer: 2 },
    { q: "Which show features the line 'Winter is Coming'?", options: ["Vikings", "The Witcher", "Game of Thrones", "The Last Kingdom"], answer: 2 },
  ],
  music: [
    { q: "What year did Michael Jackson release 'Thriller'?", options: ["1980", "1982", "1984", "1986"], answer: 1 },
    { q: "Which band was Freddie Mercury the lead vocalist of?", options: ["Led Zeppelin", "The Rolling Stones", "Queen", "Aerosmith"], answer: 2 },
    { q: "How many strings does a standard guitar have?", options: ["4", "5", "6", "8"], answer: 2 },
    { q: "Which country does Shakira come from?", options: ["Venezuela", "Mexico", "Argentina", "Colombia"], answer: 3 },
    { q: "What is the best-selling album of all time worldwide?", options: ["Led Zeppelin IV", "Thriller", "The Dark Side of the Moon", "Back in Black"], answer: 1 },
    { q: "What instrument does Elton John primarily play?", options: ["Guitar", "Drums", "Piano", "Bass"], answer: 2 },
    { q: "Which city is considered the birthplace of jazz?", options: ["New York", "Chicago", "Memphis", "New Orleans"], answer: 3 },
    { q: "In what year did The Beatles break up?", options: ["1968", "1969", "1970", "1971"], answer: 2 },
    { q: "Who is known as the 'King of Pop'?", options: ["Elvis Presley", "Prince", "Michael Jackson", "James Brown"], answer: 2 },
    { q: "Taylor Swift's first album was which genre?", options: ["Pop", "R&B", "Country", "Indie"], answer: 2 },
    { q: "What does BPM stand for in music?", options: ["Bass Per Minute", "Beats Per Minute", "Band Per Measure", "Bars Per Mix"], answer: 1 },
    { q: "Rihanna's real first name is?", options: ["Roxanne", "Robin", "Robyn", "Rachel"], answer: 2 },
    { q: "Which music genre originated in Jamaica?", options: ["Calypso", "Soca", "Reggae", "Dancehall"], answer: 2 },
    { q: "Which artist has sold the most records in history?", options: ["The Beatles", "Elvis Presley", "Michael Jackson", "Elton John"], answer: 0 },
    { q: "Who was the lead singer of Nirvana?", options: ["Dave Grohl", "Krist Novoselic", "Kurt Cobain", "Pat Smear"], answer: 2 },
  ],
  gaming: [
    { q: "Which game franchise features the character Master Chief?", options: ["Call of Duty", "Battlefield", "Halo", "Gears of War"], answer: 2 },
    { q: "What is the best-selling video game of all time?", options: ["GTA V", "Minecraft", "Tetris", "Wii Sports"], answer: 1 },
    { q: "In which game do you 'catch 'em all'?", options: ["Digimon", "Dragon Ball", "Pokémon", "Yu-Gi-Oh!"], answer: 2 },
    { q: "What year was the original PlayStation released in Japan?", options: ["1992", "1993", "1994", "1995"], answer: 2 },
    { q: "What is the name of Link's sword in The Legend of Zelda?", options: ["Excalibur", "Dragon Blade", "Master Sword", "Sacred Blade"], answer: 2 },
    { q: "What does 'FPS' stand for in gaming?", options: ["Flat Platform Strategy", "First Person Shooter", "Fast Paced Simulation", "Full Play Sequence"], answer: 1 },
    { q: "Who is the main protagonist in the God of War series?", options: ["Zeus", "Ares", "Kratos", "Poseidon"], answer: 2 },
    { q: "In Fortnite, how many players compete in a standard Battle Royale?", options: ["50", "75", "100", "200"], answer: 2 },
    { q: "Which company developed the Grand Theft Auto series?", options: ["Ubisoft", "EA Games", "Activision", "Rockstar Games"], answer: 3 },
    { q: "What colour is Mario's cap?", options: ["Blue", "Yellow", "Green", "Red"], answer: 3 },
    { q: "Which game is set in the post-apocalyptic 'Wasteland'?", options: ["The Last of Us", "Fallout", "Metro Exodus", "Days Gone"], answer: 1 },
    { q: "Which company created the Nintendo Switch?", options: ["Sony", "Microsoft", "Sega", "Nintendo"], answer: 3 },
    { q: "Pac-Man was originally released in which decade?", options: ["1960s", "1970s", "1980s", "1990s"], answer: 1 },
    { q: "Which game introduced the concept of 'battle royale' to mainstream gaming?", options: ["Fortnite", "PUBG", "H1Z1", "Warzone"], answer: 1 },
    { q: "In Minecraft, what is the final boss called?", options: ["The Wither", "The Ender Dragon", "The Elder Guardian", "Herobrine"], answer: 1 },
  ],
};
