/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FamilyActivitiesRouteImport } from './routes/family-activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayModeRouteImport } from './routes/play.$mode'
import { Route as PlayFriendsSubRouteImport } from './routes/play.friends.$sub'
import { Route as ModeModeRouteImport } from './routes/mode.$mode'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyActivitiesRoute = FamilyActivitiesRouteImport.update({
  id: '/family-activities',
  path: '/family-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayModeRoute = PlayModeRouteImport.update({
  id: '/play/$mode',
  path: '/play/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFriendsSubRoute = PlayFriendsSubRouteImport.update({
  id: '/play/friends/$sub',
  path: '/play/friends/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeModeRoute = ModeModeRouteImport.update({
  id: '/mode/$mode',
  path: '/mode/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/paywall': typeof PaywallRoute
  '/settings': typeof SettingsRoute
  '/family-activities': typeof FamilyActivitiesRoute
  '/mode/$mode': typeof ModeModeRoute
  '/play/$mode': typeof PlayModeRoute
  '/play/friends/$sub': typeof PlayFriendsSubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/paywall': typeof PaywallRoute
  '/settings': typeof SettingsRoute
  '/family-activities': typeof FamilyActivitiesRoute
  '/mode/$mode': typeof ModeModeRoute
  '/play/$mode': typeof PlayModeRoute
  '/play/friends/$sub': typeof PlayFriendsSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/paywall': typeof PaywallRoute
  '/settings': typeof SettingsRoute
  '/family-activities': typeof FamilyActivitiesRoute
  '/mode/$mode': typeof ModeModeRoute
  '/play/$mode': typeof PlayModeRoute
  '/play/friends/$sub': typeof PlayFriendsSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/paywall' | '/settings' | '/family-activities' | '/mode/$mode' | '/play/$mode' | '/play/friends/$sub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/paywall' | '/settings' | '/family-activities' | '/mode/$mode' | '/play/$mode' | '/play/friends/$sub'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/paywall'
    | '/settings'
    | '/family-activities'
    | '/mode/$mode'
    | '/play/$mode'
    | '/play/friends/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  PaywallRoute: typeof PaywallRoute
  SettingsRoute: typeof SettingsRoute
  FamilyActivitiesRoute: typeof FamilyActivitiesRoute
  ModeModeRoute: typeof ModeModeRoute
  PlayModeRoute: typeof PlayModeRoute
  PlayFriendsSubRoute: typeof PlayFriendsSubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-activities': {
      id: '/family-activities'
      path: '/family-activities'
      fullPath: '/family-activities'
      preLoaderRoute: typeof FamilyActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$mode': {
      id: '/play/$mode'
      path: '/play/$mode'
      fullPath: '/play/$mode'
      preLoaderRoute: typeof PlayModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/friends/$sub': {
      id: '/play/friends/$sub'
      path: '/play/friends/$sub'
      fullPath: '/play/friends/$sub'
      preLoaderRoute: typeof PlayFriendsSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode/$mode': {
      id: '/mode/$mode'
      path: '/mode/$mode'
      fullPath: '/mode/$mode'
      preLoaderRoute: typeof ModeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  PaywallRoute: PaywallRoute,
  SettingsRoute: SettingsRoute,
  FamilyActivitiesRoute: FamilyActivitiesRoute,
  ModeModeRoute: ModeModeRoute,
  PlayModeRoute: PlayModeRoute,
  PlayFriendsSubRoute: PlayFriendsSubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
